"""Dataset-independent cubical surface reconstruction primitives."""

from .acus_adapter import (
    AcusAdapterSettings,
    AcusWindowScene,
    load_acus_flake_window,
)
from .block import (
    BlockBounds,
    DeferredJoin,
    SurfaceBlock,
    SurfaceJoinSelection,
    assemble_surface_block_from_candidates,
    assemble_surface_hierarchy,
    assemble_surface_block,
    merge_surface_blocks,
    rebuild_surface_block,
    select_surface_joins,
    surface_block_from_retained_joins,
)
from .cluster_materialization import run_cluster_materialization
from .cell_refinement import (
    CellCandidateScore,
    CellRefinementSettings,
    ClusterCellContext,
    FrozenReplayWorkspace,
    TopologyReplay,
    anneal_topology_safe_refinement,
    evidence_utilization_summary,
    load_cluster_cell_context,
    refine_cell_neighborhood,
    replay_neighborhood_topology,
    replay_neighborhood_topology_state,
    run_cell_refinement_diagnostic,
    score_cell_candidates,
    topology_utilization_summary,
)
from .cell_refinement_variant import run_cell_refinement_materialization
from .cell_refinement_targets import (
    CellRefinementTargetSettings,
    rank_cell_refinement_targets,
    run_cell_refinement_target_ranking,
)
from .continuity import (
    JoinContinuitySettings,
    apply_join_continuity_refinement,
    run_join_continuity_refinement,
    score_join_continuity,
)
from .contracts import (
    ExtractionTileSpec,
    RawAcusSettings,
    ReconstructionWindow,
    ShardSpec,
    VolumeSource,
    VoxelBounds,
    extraction_tiles_for_shard,
    plan_extraction_tiles,
    plan_shards,
)
from .evidence import CellEvidenceTable
from .flatten import (
    ChartRaster,
    ComponentMesh,
    SurfaceChart,
    component_mesh,
    rasterize_chart,
    run_component_flattening,
    sample_depth_stack,
    tangent_atlas_chart,
)
from .gaps import GapCensus, GapTraceRecord, analyze_component_gaps
from .geometry import (
    ClippedPatch,
    DegeneratePlaneIntersection,
    EdgeCrossing,
    FaceTrace,
    PlaneEstimate,
    axial_angle_radians,
    clip_plane_to_cell,
)
from .matching import (
    EndpointAgreement,
    FaceAlignment,
    TraceMatch,
    TraceMatchSettings,
    align_face_patches,
    match_face_traces,
)
from .pipeline import run_raw_acus_pipeline
from .raw_acus import AcusCalibration, NeedleTable
from .selection import (
    ConfigurationSelection,
    configuration_options,
    optimize_configurations,
)
from .sheet_stitching import (
    SheetJoinCandidate,
    SheetJoinCatalog,
    SheetMatchingPolicy,
    SheetRestitchResult,
    SheetStitchingSettings,
    enumerate_sheet_join_catalog,
    match_sheet_join_candidate,
    restitch_sheet_graph,
    run_block_sheet_restitching,
)
from .sheet_evidence import (
    BlockSheetEvidence,
    SheetEvidenceInput,
    SheetEvidenceSettings,
    compile_block_sheet_evidence,
    read_block_sheet_evidence,
)
from .sheet_correspondence import (
    ModeCorrespondence,
    ModeCorrespondenceCatalog,
    active_mode_ids,
    catalog_block_sheet_correspondences,
    enumerate_mode_correspondences,
)
from .sheet_factors import SheetFactorSettings, compile_sheet_configuration_factors
from .sheet_configuration_solver import (
    SheetConfigurationSelection,
    SheetConfigurationSolverSettings,
    optimize_sheet_configurations,
    run_sheet_configuration_initialization,
)
from .sheet_graph_solver import replay_joint_sheet_graph
from .sheet_topology_refinement import (
    ConfigurationSeed,
    SheetTopologyEvaluation,
    SheetTopologyRefinementSettings,
    SheetTopologyWorkspace,
    choose_improving_topology_evaluation,
    frozen_exterior_join_keys,
    run_sheet_topology_refinement,
)
from .stratigraphy import ConfigurationTable, LayerModeTable
from .topology import GridEdge, GridFace, GridSpec
from .synthetic import SyntheticScene, SyntheticStackSettings, generate_synthetic_stack
from .tables import PatchTable, read_patch_shard, write_patch_shard
from .surface_graph import (
    component_statistics,
    read_surface_graph,
    write_surface_graph,
)

__all__ = [
    "ClippedPatch",
    "DegeneratePlaneIntersection",
    "DeferredJoin",
    "EdgeCrossing",
    "EndpointAgreement",
    "ExtractionTileSpec",
    "FaceTrace",
    "GridEdge",
    "GridFace",
    "GridSpec",
    "GapCensus",
    "GapTraceRecord",
    "ChartRaster",
    "ComponentMesh",
    "SurfaceChart",
    "BlockBounds",
    "AcusCalibration",
    "AcusAdapterSettings",
    "AcusWindowScene",
    "PlaneEstimate",
    "RawAcusSettings",
    "ReconstructionWindow",
    "ShardSpec",
    "VolumeSource",
    "VoxelBounds",
    "NeedleTable",
    "CellEvidenceTable",
    "CellCandidateScore",
    "CellRefinementSettings",
    "CellRefinementTargetSettings",
    "ClusterCellContext",
    "FrozenReplayWorkspace",
    "TopologyReplay",
    "anneal_topology_safe_refinement",
    "ConfigurationTable",
    "LayerModeTable",
    "JoinContinuitySettings",
    "ConfigurationSelection",
    "configuration_options",
    "component_mesh",
    "FaceAlignment",
    "TraceMatch",
    "TraceMatchSettings",
    "SurfaceBlock",
    "SurfaceJoinSelection",
    "SheetJoinCandidate",
    "SheetJoinCatalog",
    "SheetMatchingPolicy",
    "SheetRestitchResult",
    "SheetStitchingSettings",
    "SheetEvidenceInput",
    "SheetEvidenceSettings",
    "BlockSheetEvidence",
    "ModeCorrespondence",
    "ModeCorrespondenceCatalog",
    "SheetFactorSettings",
    "SheetConfigurationSelection",
    "SheetConfigurationSolverSettings",
    "ConfigurationSeed",
    "SheetTopologyEvaluation",
    "SheetTopologyRefinementSettings",
    "SheetTopologyWorkspace",
    "SyntheticScene",
    "SyntheticStackSettings",
    "PatchTable",
    "align_face_patches",
    "analyze_component_gaps",
    "assemble_surface_block",
    "assemble_surface_block_from_candidates",
    "assemble_surface_hierarchy",
    "axial_angle_radians",
    "clip_plane_to_cell",
    "generate_synthetic_stack",
    "match_face_traces",
    "load_acus_flake_window",
    "merge_surface_blocks",
    "rebuild_surface_block",
    "select_surface_joins",
    "surface_block_from_retained_joins",
    "optimize_configurations",
    "rasterize_chart",
    "extraction_tiles_for_shard",
    "plan_extraction_tiles",
    "plan_shards",
    "read_patch_shard",
    "write_patch_shard",
    "run_raw_acus_pipeline",
    "run_block_sheet_restitching",
    "compile_block_sheet_evidence",
    "read_block_sheet_evidence",
    "catalog_block_sheet_correspondences",
    "enumerate_mode_correspondences",
    "active_mode_ids",
    "compile_sheet_configuration_factors",
    "optimize_sheet_configurations",
    "run_sheet_configuration_initialization",
    "replay_joint_sheet_graph",
    "choose_improving_topology_evaluation",
    "frozen_exterior_join_keys",
    "run_sheet_topology_refinement",
    "run_join_continuity_refinement",
    "score_join_continuity",
    "apply_join_continuity_refinement",
    "run_component_flattening",
    "run_cluster_materialization",
    "run_cell_refinement_diagnostic",
    "run_cell_refinement_materialization",
    "run_cell_refinement_target_ranking",
    "load_cluster_cell_context",
    "score_cell_candidates",
    "rank_cell_refinement_targets",
    "refine_cell_neighborhood",
    "replay_neighborhood_topology",
    "replay_neighborhood_topology_state",
    "evidence_utilization_summary",
    "topology_utilization_summary",
    "component_statistics",
    "read_surface_graph",
    "write_surface_graph",
    "sample_depth_stack",
    "tangent_atlas_chart",
    "enumerate_sheet_join_catalog",
    "match_sheet_join_candidate",
    "restitch_sheet_graph",
]
